# Generated by Django 4.2.10 on 2026-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessment',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
