# Generated by Django 4.2.10 on 2026-03-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignmentdiscussionpost_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
    ]
