# Generated by Django 4.2.10 on 2026-03-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('assignment_posted', 'Assignment Posted'), ('feedback_received', 'Feedback Received'), ('feedback_given', 'Feedback Given'), ('course_invited', 'Course Invited')], max_length=64),
        ),
    ]
